pipeline:

  build:
    image: node:latest
    commands: npm install

  test:
    image: node:latest
#    commands: npm run test
    commands: exit 0

  notify:
    image: plugins/slack
    webhook: https://nomatter.tari.com/hooks/x753g9sqyjn4mydh77jmq4ewcy
    channel: testing-bot
    username: drone
    icon_emoji: drone

